name: sof_user_app
description: A project to build a clean architecture.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.12.0
  retrofit: ^4.0.1
  get_it: ^7.2.0
  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.1.0
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  intl: ^0.18.0
  flutter_bloc: ^8.1.2
  logger: ^1.3.0
  pull_to_refresh_flutter3: ^2.0.1
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  retrofit_generator: '>=5.0.0 <6.0.0'

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sof_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
